package define

type ItemSetId int
type ItemId int
type PowerId int
type StatusId uint64

const (
	ALIGN_TOPLEFT = iota
	ALIGN_TOP
	ALIGN_TOPRIGHT
	ALIGN_LEFT
	ALIGN_CENTER
	ALIGN_RIGHT
	ALIGN_BOTTOMLEFT
	ALIGN_BOTTOM
	ALIGN_BOTTOMRIGHT
	ALIGN_FRAME_TOPLEFT
	ALIGN_FRAME_TOP
	ALIGN_FRAME_TOPRIGHT
	ALIGN_FRAME_LEFT
	ALIGN_FRAME_CENTER
	ALIGN_FRAME_RIGHT
	ALIGN_FRAME_BOTTOMLEFT
	ALIGN_FRAME_BOTTOM
	ALIGN_FRAME_BOTTOMRIGHT
)
