package platform

const (
	CONFIG_MENU_TYPE_BASE = iota
	CONFIG_MENU_TYPE_DESKTOP
	CONFIG_MENU_TYPE_DESKTOP_NO_VIDEO
)

const (
	VIDEO_COUNT     = 11
	AUDIO_COUNT     = 2
	INTERFACE_COUNT = 16
	INPUT_COUNT     = 9
	MISC_COUNT      = 2
)

const (
	VIDEO_RENDERER = iota
	VIDEO_FULLSCREEN
	VIDEO_HWSURFACE
	VIDEO_VSYNC
	VIDEO_TEXTURE_FILTER
	VIDEO_DPI_SCALING
	VIDEO_PARALLAX_LAYERS
	VIDEO_ENABLE_GAMMA
	VIDEO_GAMMA
	VIDEO_MAX_RENDER_SIZE
	VIDEO_FRAME_LIMIT
)

const (
	AUDIO_SFX = iota
	AUDIO_MUSIC
)

const (
	INTERFACE_LANGUAGE = iota
	INTERFACE_SUBTITLES
	INTERFACE_COLORBLIND
	INTERFACE_MINIMAP_MODE
	INTERFACE_LOOT_TOOLTIPS
	INTERFACE_AUTO_EQUIP
	INTERFACE_ITEM_COMPARE_TIPS
	INTERFACE_LOW_HP_WARNING_TYPE
	INTERFACE_LOW_HP_THRESHOLD
	INTERFACE_COMBAT_TEXT
	INTERFACE_STATBAR_LABELS
	INTERFACE_STATBAR_AUTOHIDE
	INTERFACE_HARDWARE_CURSOR
	INTERFACE_ENTITY_MARKERS
	INTERFACE_SHOW_FPS
	INTERFACE_DEV_MODE
)

const (
	INPUT_MOUSE_MOVE = iota
	INPUT_MOUSE_MOVE_SWAP
	INPUT_MOUSE_MOVE_ATTACK
	INPUT_MOUSE_AIM
	INPUT_NO_MOUSE
	INPUT_JOYSTICK
	INPUT_JOYSTICK_DEADZONE
	INPUT_TOUCH_CONTROLS
	INPUT_TOUCH_SCALE
)

const (
	MISC_KEYBINDS = iota
	MISC_MODS
)
