package fontengine

const (
	COLOR_WHITE = iota
	COLOR_BLACK
	COLOR_MENU_NORMAL
	COLOR_MENU_BONUS
	COLOR_MENU_PENALTY
	COLOR_WIDGET_NORMAL
	COLOR_WIDGET_DISABLED
	COLOR_COMBAT_GIVEDMG
	COLOR_COMBAT_TAKEDMG
	COLOR_COMBAT_CRIT
	COLOR_COMBAT_BUFF
	COLOR_COMBAT_MISS
	COLOR_REQUIREMENTS_NOT_MET
	COLOR_ITEM_BONUS
	COLOR_ITEM_PENALTY
	COLOR_ITEM_FLAVOR
	COLOR_HARDCORE_NAME
)

const (
	JUSTIFY_LEFT = iota
	JUSTIFY_RIGHT
	JUSTIFY_CENTER
)
